/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DossierRouteImport } from './routes/dossier'
import { Route as MappaRouteImport } from './routes/mappa'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as UrbanGoRouteImport } from './routes/urban-go'
import { Route as ArticoliIdRouteImport } from './routes/articoli.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DossierRoute = DossierRouteImport.update({
  id: '/dossier',
  path: '/dossier',
  getParentRoute: () => rootRouteImport,
} as any)
const MappaRoute = MappaRouteImport.update({
  id: '/mappa',
  path: '/mappa',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const UrbanGoRoute = UrbanGoRouteImport.update({
  id: '/urban-go',
  path: '/urban-go',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticoliIdRoute = ArticoliIdRouteImport.update({
  id: '/articoli/$id',
  path: '/articoli/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dossier': typeof DossierRoute
  '/mappa': typeof MappaRoute
  '/partner': typeof PartnerRoute
  '/urban-go': typeof UrbanGoRoute
  '/articoli/$id': typeof ArticoliIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dossier': typeof DossierRoute
  '/mappa': typeof MappaRoute
  '/partner': typeof PartnerRoute
  '/urban-go': typeof UrbanGoRoute
  '/articoli/$id': typeof ArticoliIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dossier': typeof DossierRoute
  '/mappa': typeof MappaRoute
  '/partner': typeof PartnerRoute
  '/urban-go': typeof UrbanGoRoute
  '/articoli/$id': typeof ArticoliIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/dossier' | '/mappa' | '/partner' | '/urban-go' | '/articoli/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dossier' | '/mappa' | '/partner' | '/urban-go' | '/articoli/$id'
  id:
    | '__root__'
    | '/'
    | '/dossier'
    | '/mappa'
    | '/partner'
    | '/urban-go'
    | '/articoli/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DossierRoute: typeof DossierRoute
  MappaRoute: typeof MappaRoute
  PartnerRoute: typeof PartnerRoute
  UrbanGoRoute: typeof UrbanGoRoute
  ArticoliIdRoute: typeof ArticoliIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dossier': {
      id: '/dossier'
      path: '/dossier'
      fullPath: '/dossier'
      preLoaderRoute: typeof DossierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mappa': {
      id: '/mappa'
      path: '/mappa'
      fullPath: '/mappa'
      preLoaderRoute: typeof MappaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/urban-go': {
      id: '/urban-go'
      path: '/urban-go'
      fullPath: '/urban-go'
      preLoaderRoute: typeof UrbanGoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articoli/$id': {
      id: '/articoli/$id'
      path: '/articoli/$id'
      fullPath: '/articoli/$id'
      preLoaderRoute: typeof ArticoliIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DossierRoute: DossierRoute,
  MappaRoute: MappaRoute,
  PartnerRoute: PartnerRoute,
  UrbanGoRoute: UrbanGoRoute,
  ArticoliIdRoute: ArticoliIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
